blogapp/blogapp/admin_panel/urls.py
from django.urls import path
from . import views
from .views import ajax_manage_users, ajax_manage_blogs, manage_users, manage_blogs

app_name = 'admin_panel'

urlpatterns = [
    path('update_status/', views.update_status, name='update_status'),
    path('users/', manage_users, name='manage_users'),
    path('blogs/', manage_blogs, name='manage_blogs'),
    path('ajax/manage-users/', ajax_manage_users, name='ajax_manage_users'),
    path('ajax/manage-blogs/', ajax_manage_blogs, name='ajax_manage_blogs'),

]
    # path('approve_user/<int:user_id>/', views.approve_user, name='approve_user'),
    # path('approve_blog/<int:blog_id>/', views.approve_blog, name='approve_blog'),
    # path('inactive_user/<int:user_id>/', views.inactive_user, name='inactive_user'),
    # path('inactive_blog/<int:blog_id>/', views.inactive_blog, name='inactive_blog'),
    # path('users/', views.manage_users, name='manage_users'),
    # path('blogs/', views.manage_blogs, name='manage_blogs'),
    # path('ajax-test/', views.ajax_test_view, name='ajax_test')
    # path('activate_user/', views.activate_user, name='activate_user'),
    # path('deactivate_user/', views.deactivate_user, name='deactivate_user'),
    # path('activate_blog/', views.activate_blog, name='activate_blog'),
    # path('deactivate_blog/', views.deactivate_blog, name='deactivate_blog'),

blogapp/blogapp/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('blogs/<slug:slug>/comments/', views.comments_view, name='comments'),
    path("", views.index, name='home'),
    path("index", views.index),
    path("blogs", views.blog, name='blogs'),
    path('blogs/<slug:slug>/', views.blog_details, name='blog_details'),
    path('add/', views.add_blog, name='add_blog'),
    path('load-filtered-blogs/', views.load_filtered_blogs, name='load_filtered_blogs'),
    # path('load-more-blogs/', views.load_more_blogs, name='load_more_blogs'),
    # path('filter-blogs/', views.filter_blogs, name='filter_blogs'),
]

blogapp/blogapp/blogapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import i18n




urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('account.urls')),
    path('admin_panel/', include('admin_panel.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)









# urlpatterns += i18n_patterns(
#     path(_('admin/'), admin.site.urls),
#     path('', include('blog.urls')), 
#     path(_('account/'), include('account.urls')), 
#     path(_('admin_panel/'), include('admin_panel.urls')),  
# ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/blogapp/admin_panel/models.py
from django.db import models

# Create your models here.

blogapp/blogapp/admin_panel/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from blog.models import User, Blog
from django.contrib import messages
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
# from django.core.paginator import Paginator
# from django.views.decorators.http import require_GET
from blogapp.decorators import superuser_required

def update_status(request):
    if request.method == "POST":
        item_ids = request.POST.getlist('ids[]')  
        item_type = request.POST.get('type')
        action = request.POST.get('action')

        # print(f"Gelen istek - item_type: {item_type}, action: {action}, ids: {item_ids}")

        if item_type == 'user':
            try:
                users = User.objects.filter(id__in=item_ids)  
                is_active_status = True if action == 'activate' else False
                
                for user in users:
                    user.is_active = is_active_status
                    user.save()

                return JsonResponse({'success': True, 'message': f"Kullanıcılar {action} edildi"})
            except User.DoesNotExist:
                return JsonResponse({'success': False, 'message': "Kullanıcılar bulunamadı"})

        elif item_type == 'blog':
            try:
                blogs = Blog.objects.filter(id__in=item_ids)  
                is_active_status = True if action == 'activate' else False
                
                for blog in blogs:
                    blog.is_active = is_active_status
                    blog.save()

                return JsonResponse({'success': True, 'message': f"Bloglar {action} edildi"})
            except Blog.DoesNotExist:
                return JsonResponse({'success': False, 'message': "Bloglar bulunamadı"})

    return JsonResponse({'success': False, 'message': "Geçersiz istek"})

    
def ajax_manage_users(request):
    users = User.objects.all().values('id', 'username', 'email', 'is_active')  
    user_list = list(users)  
    return JsonResponse(user_list, safe=False)  

def ajax_manage_blogs(request):
    blogs = Blog.objects.all().values('id', 'title', 'author__username', 'category__name', 'is_active')
    blog_list = list(blogs)  
    return JsonResponse(blog_list, safe=False)

# @require_GET
# def ajax_test_view(request):
#     data = {'message': 'AJAX çalışıyor!'}
#     return JsonResponse(data)

@login_required
@superuser_required
def manage_users(request):
    users = User.objects.all() 
    return render(request, 'admin_panel/manage_users.html', {'users': users})


@login_required
@superuser_required
def manage_blogs(request):
    blogs = Blog.objects.all()
    return render(request, 'admin_panel/manage_blogs.html', {'blogs': blogs})

blogapp/blogapp/admin_panel/templates/admin_panel/manage_blogs.html
{% extends 'admin_base.html' %}
{% load static %}
{% load i18n %}

{% block title %}Admin-Panel{% endblock %}

{% block css_files %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css">
    <style>
        body {
            background-color: #343a40; 
            color: #ffffff; 
        }

        .table {
            background-color: #ffffff;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1); 
        }

        .table thead th {
            background-color: #6c757d; 
            color: white; 
        }

        .table-striped tbody tr:nth-of-type(odd) {
            background-color: #f2f2f2; 
        }

        .table tbody tr.selected {
            background-color: #d1ecf1;  
        }

        .list-group-item {
            background-color: #495057; 
            color: #ffffff; 
            border-radius: 5px; 
        }

        .list-group-item:hover {
            background-color: #6c757d;
            color: #ffffff;
        }

        .btn-success {
            background-color: #28a745; 
            border-color: #28a745;
        }

        .btn-danger {
            background-color: #dc3545; 
            border-color: #dc3545;
        }
    </style>
{% endblock %}

{% block content %}
<div class="container-fluid mt-5 row">
    {% include 'partials/msg.html' %}
    <div class="col-md-3 list-group">  
        <a href="{% url 'home' %}" class="list-group-item list-group-item-action">{% trans "Anasayfa" %}</a>
        <a href="{% url 'admin_panel:manage_blogs' %}" class="list-group-item list-group-item-action">{% trans "Blog Yönetimi" %}</a>
        <a href="{% url 'admin_panel:manage_users' %}" class="list-group-item list-group-item-action">{% trans "Kullanıcı Yönetimi" %}</a>
    </div>
    <div class="col-md-9">
        <div class="row align-items-center">
            <div class="col d-flex justify-content-between">
                <h2>{% trans "Blog Yönetimi" %}</h2>
                <div>
                    <select id="actionSelect">
                        <option value="activate">{% trans "Aktif Et" %}</option>
                        <option value="deactivate">{% trans "İnaktif Et" %}</option>
                    </select>
                    <button id="applyButton" class="btn btn-primary my-3">{% trans "Uygula" %}</button>
                </div>
            </div>
        </div>
        <table id="blogsTable" class="table table-dark table-striped table-hover table-bordered">
            <thead>
                <tr>
                    <th><input type="checkbox" id="selectAll"></th>
                    <th>ID</th>
                    <th>{% trans "Başlık" %}</th>
                    <th>{% trans "Durum" %}</th>
                    <th>{% trans "İşlemler" %}</th>
                </tr>
            </thead>
        </table>
    </div>
</div>
{% endblock %}

{% block js_files %}
<script>
    const updateStatusUrl = "{% url 'admin_panel:update_status' %}";
    const csrfToken = '{{ csrf_token }}';

    $('#selectAll').on('click', function() {
        var is_checked = $(this).prop('checked');
        $('#blogsTable tbody input[type="checkbox"]').prop('checked', is_checked);
        if (is_checked) {
            $('#blogsTable tbody tr').addClass('selected');
        } else {
            $('#blogsTable tbody tr').removeClass('selected');
        }
    });
    
    $('#applyButton').on('click', function() {
        const selectedBlogIds = [];
        
        $('#blogsTable tbody input[type="checkbox"]:checked').each(function() {
            selectedBlogIds.push($(this).data('blog-id'));
        });
        
        if (selectedBlogIds.length === 0) {
            showAlert('warning', 'Lütfen en az bir blog seçin.');
            return;
        }

        const action = $('#actionSelect').val();  

        $.ajax({
            url: updateStatusUrl,
            type: 'POST',
            data: {
                'ids': selectedBlogIds,
                'type': 'blog', 
                'action': action,  
                'csrfmiddlewaretoken': csrfToken
            },
            success: function(response) {
                if (response.success) {
                    loadBlogs(); 
                    showAlert('success', response.message);
                } else {
                    showAlert('danger', response.message);
                }
            },
            error: function() {
                showAlert('danger', 'Toplu durum güncellenirken bir hata oluştu.');
            }
        });
    });

    
    let blogsTable;

    $(document).ready(function(){
        blogsTable = $('#blogsTable').DataTable({
            language:{
                url: "//cdn.datatables.net/plug-ins/1.10.21/i18n/Turkish.json"
            },
            "createdRow": function(row, data, dataIndex) {
                $(row).attr('id', 'row-' + data[1]);
            }
        });

        loadBlogs();


        $('#blogsTable tbody').on('click', 'tr', function() {
            var checkbox = $(this).find('input[type="checkbox"]');
            checkbox.prop('checked', !checkbox.prop('checked'));
            $(this).toggleClass('selected');  
        });
    });

    function updateStatus(itemId, itemType, action) {
        console.log(`updateStatus called with: itemId=${itemId}, itemType=${itemType}, action=${action}`);
        $('.alert').remove();


        $.ajax({
            url: updateStatusUrl,
            type: 'POST',
            data: {
                'ids[]': itemId,
                'type': itemType,
                'action': action,
                'csrfmiddlewaretoken': csrfToken
            },
            success: function(response) {
                if (response.success) {
                    const rowSelector = `#row-${itemId}`;
                    const row = blogsTable.row(rowSelector);
                    
                    if (row.length) {
                        const rowData = row.data();
                        const newStatus = action === 'activate' ? 'Aktif' : 'Pasif';
                        const newButton = action === 'activate' 
                            ? `<button onclick="deactivateBlog(${itemId})" class="btn btn-danger btn-sm">Deaktive Et</button>`
                            : `<button onclick="activateBlog(${itemId})" class="btn btn-success btn-sm">Aktif Et</button>`;
                        
                        rowData[3] = newStatus;
                        rowData[4] = newButton;
                        
                        row.data(rowData).draw(false);
                    }
                    
                    showAlert('success', response.message);
                } else {
                    showAlert('danger', response.message);
                }
            },
            error: function() {
                showAlert('danger', 'Durum güncellenirken bir hata oluştu.');
            }
        });
    }
   
    function showAlert(type, message) {
        $('.alert').remove();

        const alertHtml = `
            <div class="alert alert-${type} alert-dismissible fade show" role="alert">
                ${message}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        `;

        $('.col-md-3').prepend(alertHtml);

        setTimeout(() => {
            $('.alert').fadeOut('slow', function(){
                $(this).remove();
            } )
        }, 3000);
    }

    function activateBlog(blogId, event){
        updateStatus(blogId, 'blog', 'activate');
    }
  
    function deactivateBlog(blogId, event){
        updateStatus(blogId, 'blog', 'deactivate');
    }

    function loadBlogs() {
        $.ajax({
            url: "{% url 'admin_panel:ajax_manage_blogs' %}",
            type: "GET",
            success: function(response) {
                blogsTable.clear();

                response.forEach(function(blog){
                    var status = blog.is_active ? 'Aktif' : 'Pasif';
                    var actions = blog.is_active
                        ? `<button onclick="deactivateBlog(${blog.id})" class="btn btn-danger btn-sm">Deaktive Et</button>`
                        : `<button onclick="activateBlog(${blog.id})" class="btn btn-success btn-sm">Aktif Et</button>`;
                    
                    var row = [
                        `<input type="checkbox" class="blogCheckbox" data-blog-id="${blog.id}">`,
                        blog.id,
                        blog.title,
                        status,
                        actions   
                    ];

                    blogsTable.row.add(row);
                });

                blogsTable.draw();
            },
            error: function() {
                showAlert('danger', 'blog verileri yüklenemedi');
            }
        });
    }

</script>
{% endblock %}




<!-- 
datatable kullandığımız için bu kısmı kaldırdık.
<nav>
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="First">&laquo;</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Önceki</a>
            </li>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            <li class="page-item {% if page_obj.number == num %}active{% endif %}">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Sonraki</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">&raquo;</a>
            </li>
        {% endif %}
    </ul>
</nav> -->

blogapp/blogapp/admin_panel/templates/admin_panel/manage_users.html
{% extends 'admin_base.html' %}
{% load static %}
{% load i18n %}

{% block title %}Admin-Panel{% endblock %}

{% block css_files %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css">
    <style>
        body {
            background-color: #343a40; 
            color: #ffffff; 
        }

        .table {
            background-color: #ffffff;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1); 
        }

        .table thead th {
            background-color: #6c757d; 
            color: white; 
        }

        .table tbody tr.selected {
            background-color: #d1ecf1;  
        }

        .list-group-item {
            background-color: #495057; 
            color: #ffffff; 
            border-radius: 5px; 
        }

        .list-group-item:hover {
            background-color: #6c757d;
            color: #ffffff;
        }

        .btn-success {
            background-color: #28a745; 
            border-color: #28a745;
        }

        .btn-danger {
            background-color: #dc3545; 
            border-color: #dc3545;
        }

    </style>
{% endblock %}

{% block content %}
{% include 'partials/msg.html' %}

<div class="container-fluid mt-5 row">
    
    <div class="col-md-3 list-group">  
        <a href="{% url 'home' %}" class="list-group-item list-group-item-action">{% trans "Anasayfa" %}</a>
        <a href="{% url 'admin_panel:manage_blogs' %}" class="list-group-item list-group-item-action">{% trans "Blog Yönetimi" %}</a>
        <a href="{% url 'admin_panel:manage_users' %}" class="list-group-item list-group-item-action">{% trans "Kullanıcı Yönetimi" %}</a>
    </div>
    <div class="col-md-9">
        <div class="row align-items-center">
            <div class="col d-flex justify-content-between">
                <h2>{% trans "Kullanıcı Yönetimi" %}</h2>
                <div>
                    <select id="actionSelect">
                        <option value="activate">{% trans "Aktif Et" %}</option>
                        <option value="deactivate">{% trans "İnaktif Et" %}</option>
                    </select>
                    <button id="applyButton" class="btn btn-primary my-3">{% trans "Uygula" %}</button>
                </div>
            </div>
        </div>
        <table id="usersTable" class="table table-dark table-striped table-hover table-bordered">
            <thead>
                <tr>
                    <th><input type="checkbox" id="selectAll"></th>
                    <th>ID</th>
                    <th>{% trans "Kullanıcı Adı" %}</th>
                    <th>Email</th>
                    <th>{% trans "Durum" %}</th>
                    <th>{% trans "İşlemler" %}</th>
                </tr>
            </thead>
        </table>
    </div>
</div>
{% endblock %}

{% block js_files %}

<script>
    const updateStatusUrl = "{% url 'admin_panel:update_status' %}";
    const csrfToken = '{{ csrf_token }}';

    $('#selectAll').on('click', function() {
        var is_checked = $(this).prop('checked');
        $('#usersTable tbody input[type="checkbox"]').prop('checked', is_checked);
        if (is_checked) {
            $('#usersTable tbody tr').addClass('selected');
        } else {
            $('#usersTable tbody tr').removeClass('selected');
        }
    });

    $('#applyButton').on('click', function() {
        const selectedUserIds = [];
        
        $('#usersTable tbody input[type="checkbox"]:checked').each(function() {
            selectedUserIds.push($(this).data('user-id'));
        });
        
        if (selectedUserIds.length === 0) {
            showAlert('warning', 'Lütfen en az bir user seçin.');
            return;
        }

        const action = $('#actionSelect').val();  

        $.ajax({
            url: updateStatusUrl,
            type: 'POST',
            data: {
                'ids[]': selectedUserIds,
                'type': 'user', 
                'action': action,  
                'csrfmiddlewaretoken': csrfToken
            },
            success: function(response) {
                if (response.success) {
                    loadUsers(); 
                    showAlert('success', response.message);
                } else {
                    showAlert('danger', response.message);
                }
            },
            error: function() {
                showAlert('danger', 'Toplu durum güncellenirken bir hata oluştu.');
            }
        });
    });

    let usersTable;

    $(document).ready(function() {
        usersTable = $('#usersTable').DataTable({
            language: {
                url: "//cdn.datatables.net/plug-ins/1.10.21/i18n/Turkish.json"
            },
            "createdRow": function(row, data, dataIndex) {
                $(row).attr('id', 'row-' + data[1]);
            }
        });
        
        loadUsers();

        $('#usersTable tbody').on('click','tr', function(){
            var checkbox = $(this).find('input[type="checkbox"]');
            checkbox.prop('checked', !checkbox.prop('checked'));
            $(this).toggleClass('selected');
        });
    });

    function updateStatus(itemId, itemType, action) {
        console.log(`updateStatus called with: itemId=${itemId}, itemType=${itemType}, action=${action}`);
        $('.alert').remove();
        
        $.ajax({
            url: updateStatusUrl,
            type: "POST",
            data: {
                'ids[]': itemId,
                'type': itemType,
                'action': action,
                'csrfmiddlewaretoken': csrfToken
            },
            success: function(response){
                if (response.success) {
                    const rowSelector = `#row-${itemId}`;
                    const row = usersTable.row(rowSelector);

                    if(row.length){
                        const rowData = row.data();
                        const newStatus = action === 'activate' ? 'Aktif' : 'Pasif';
                        const newButton = action === 'activate' 
                            ? `<button onclick="deactivateUser(${itemId})" class="btn btn-danger btn-sm">Deaktive Et</button>`
                            : `<button onclick="activateUser(${itemId})" class="btn btn-success btn-sm">Aktif Et</button>`;
                        
                        rowData[4] = newStatus;
                        rowData[5] = newButton;
                        
                        row.data(rowData).draw(false);
                    }

                    showAlert('success',  response.message);
                } else {
                    showAlert('danger', response.message);
                }
            },
            error:function(){
                showAlert('danger', 'durum güncellenirken bir hata oluştur.')
            }
        });
    }

    function showAlert(type, message) {
        $('.alert').remove();
        
        const alertHTML = `
            <div class="alert alert-${type} alert-dismissible fade show" role="alert">
                ${message}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        `;
        
        $('.col-md-3').prepend(alertHTML);
        
        setTimeout(() => {
            $('.alert').fadeOut('slow', function() {
                $(this).remove();
            });
        }, 3000);
    }

    function loadUsers() {
        $.ajax({
            url: "{% url 'admin_panel:ajax_manage_users' %}",
            type: "GET",
            success: function(response) {
                usersTable.clear();

                response.forEach(function(user) {
                    var status = user.is_active ? 'Aktif' : 'Pasif';
                    var actions = user.is_active
                        ? `<button onclick="deactivateUser(${user.id})" class="btn btn-danger btn-sm">Deaktive Et</button>`
                        : `<button onclick="activateUser(${user.id})" class="btn btn-success btn-sm">Aktif Et</button>`;

                    var row = [
                        `<input type="checkbox" class="userCheckbox" data-user-id="${user.id}">`,
                        user.id,
                        user.username,
                        user.email,
                        status,
                        actions
                    ];

                    usersTable.row.add(row);
                });

                usersTable.draw();
            },
            error: function() {
                showAlert('danger', 'Kullanıcı verileri yüklenemedi.');
            }
        });
    }
   
    function activateUser(userId, event) {
        updateStatus(userId, 'user', 'activate');
    }

    function deactivateUser(userId, event) {
        updateStatus(userId, 'user', 'deactivate');
    }

</script>
{% endblock %}


<!-- <td>
    {% if not user.is_active %}
        <a href="{% url 'admin_panel:approve_user' user.id %}" class="btn btn-sm btn-success" data-toggle="tooltip" title="Blogu onaylayın"><i class="fas fa-check"></i> Onayla</a>
    {% endif %}
    {% if user.is_active %}
        <a href="{% url 'admin_panel:inactive_user' user.id %}" class="btn btn-sm btn-danger" data-toggle="tooltip" title="İnaktif edin"><i class="fas fa-ban"></i> İnaktif Et</a>
    {% endif %}
</td> -->


<!--
datatable kullandığımız için bu kısmı kaldırdık.
<nav>
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="First">&laquo;</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Önceki</a>
            </li>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            <li class="page-item {% if page_obj.number == num %}active{% endif %}">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </li>
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Sonraki</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">&raquo;</a>
            </li>
        {% endif %}
    </ul>
</nav> -->


<!-- <div>
    <button id="ajaxTestButton">AJAX Testi Yap</button>
    <p id="ajaxTestResult"></p>

<script>
    document.getElementById("ajaxTestButton").addEventListener("click", function() {
        $.ajax({
            url: "{% url 'ajax_test' %}",
            type: "GET",
            success: function(response) {
                document.getElementById("ajaxTestResult").innerText = response.message;
            },
            error: function(xhr, status, error) {
                document.getElementById("ajaxTestResult").innerText = "AJAX isteği başarısız!";
            }
        });
    });
</script>

</div> -->